version: "3.1"

services:
  db:
    image: mariadb:10.3.27
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bestell_user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bestell_db
    volumes:
      - ./var/db-data:/var/lib/mysql:rw
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
